eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
      
spring:
  kafka:
    bootstrap-servers: kafka:29092
  datasource:
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}